spring:
  application:
    name: Todo
  datasource:
    url: jdbc:h2:mem:todolist
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

ruben:
  openapi:
    dev-url: localhost:8080
    prod-url: localhost:8080
